window.addEventListener("load", () => {
   saveData()
   saveTeamData()
})



 
 
 // CSK
 const playerDetails = [
  {
    id: 1,
    playerName: "MS Dhoni",
    from: "CSK",
    price: "12 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage: "./assests/playerImages/1.webp",
    description: "Batsman",
  },
  {
    id: 2,
    playerName: "C Hari Nishaanth",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/2.webp",
    description: "Batsman",
  },
  {
    id: 3,
    playerName: "Devon Conway",
    from: "CSK",
    price: "1 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/3.webp",
    description: "Batsman",
  },
  {
    id: 4,
    playerName: "Robin Uthappa",
    from: "CSK",
    price: "2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/4.webp",
    description: "Batsman",
  },
  {
    id: 5,
    playerName: "Ruturaj Gaikwad",
    from: "CSK",
    price: "6 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/5.webp",
    description: "Batsman",
  },
  {
    id: 6,
    playerName: "Subhranshu Senapati",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/6.webp",
    description: "Batsman",
  },
  {
    id: 7,
    playerName: "Ambati Rayudu",
    from: "CSK",
    price: "6.75 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/7.webp",
    description: "Batsman",
  },
  {
    id: 8,
    playerName: "Ravindra Jadeja",
    from: "CSK",
    price: "16 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/8.webp",
        description: "All-rounder",
  },
  {
    id: 9,
    playerName: "Narayan Jagadeesan",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/9.webp",
    description: "Batsman",
  },
  {
    id: 10,
    playerName: "Chris Jordan",
    from: "CSK",
    price: "3.6 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/10.webp",
    description: "Bowler",
  },
  {
    id: 11,
    playerName: "Dwaine Pretorius",
    from: "CSK",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/11.webp",
    description: "All-rounder",
  },
  {
    id: 12,
    playerName: "Dwayne Bravo",
    from: "CSK",
    price: "4.4 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/12.webp",
    description: "All-rounder",
  },
  {
    id: 13,
    playerName: "Mitchell Santner",
    from: "CSK",
    price: "1.9 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/13.webp",
    description: "All-rounder",
  },
  {
    id: 14,
    playerName: "K Bhagath Varma",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/14.webp",
    description: "All-rounder",
  },
  {
    id: 15,
    playerName: "Moeen Ali",
    from: "CSK",
    price: "8 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/15.webp",
    description: "All-rounder",
  },
  {
    id: 16,
    playerName: "Rajvardhan Hangargekar",
    from: "CSK",
    price: "1.5 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/16.webp",
    description: "Bowler",
  },
  {
    id: 17,
    playerName: "Shivam Dube",
    from: "CSK",
    price: "4 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/17.webp",
    description: "All-rounder",
  },
  {
    id: 18,
    playerName: "Adam Milne",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/18.webp",
    description: "Bowler",
  },
  {
    id: 19,
    playerName: "Deepak Chahar",
    from: "CSK",
    price: "14 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/19.webp",
    description: "Bowler",
  },
  {
    id: 20,
    playerName: "KM Asif",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/20.webp",
    description: "Bowler",
  },
  {
    id: 21,
    playerName: "Maheesh Theekshana",
    from: "CSK",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/21.webp",
    description: "Bowler",
  },
  {
    id: 22,
    playerName: "Mukesh Choudhary",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/22.webp",
    description: "Bowler",
  },
  {
    id: 23,
    playerName: "Prashant Solanki",
    from: "CSK",
    price: "1.2 Cr",
    isPlaying: false,
    playerImage:  "./assests/playerImages/23.webp",
    description: "Bowler",
  },
  {
    id: 24,
    playerName: "Simarjeet Singh",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/24.webp",
    description: "Bowler",
  },
  {
    id: 25,
    playerName: "Tushar Deshpande",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/25.webp",
    description: "Bowler",
  },
  {
    id: 26,
    playerName: "Matheesha Pathirana",
    from: "CSK",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/26.webp",
    description: "Bowler",
  },
  {
    id: 27,
    playerName: "Rishabh Pant",
    from: "DC",
    price: "16 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/27.webp",
    description: "Batsman",
  },
  {
    id: 28,
    playerName: "Ashwin Hebbar",
    from: "DC",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/28.webp" ,
    description: "Batsman",
  },
  {
    id: 29,
    playerName: "David Warner",
    from: "DC",
    price: "6.25 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/29.webp",
    description: "Batsman",
  },
  {
    id: 30,
    playerName: "Mandeep Singh",
    from: "DC",
    price: "1.1 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/30.webp",
    description: "All-rounder",
  },
  {
    id: 31,
    playerName: "Prithvi Shaw",
    from: "DC",
    price: "7.5 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/31.webp",
    description: "Batsman",
  },
  {
    id: 32,
    playerName: "Rovman Powell",
    from: "DC",
    price: "2.8 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/32.webp",
    description: "Batsman",
  },
  {
    id: 33,
    playerName: "K.S Bharat",
    from: "DC",
    price: "2 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/33.webp",
    description: "Batsman",
  },
  {
    id: 34,
    playerName: "Tim Seifert",
    from: "DC",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/34.webp",
    description: "Batsman",
  },
  {
    id: 35,
    playerName: "Axar Patel",
    from: "DC",
    price: "9 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/35.webp",
    description: "All-rounder",
  },
  {
    id: 36,
    playerName: "Kamlesh Nagarkoti",
    from: "DC",
    price: "1.1 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/36.webp",
    description: "Bowler",
  },
  {
    id: 37,
    playerName: "Lalit Yadav",
    from: "DC",
    price: "0.65 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/37.webp",
    description: "All-rounder",
  },
  {
    id: 38,
    playerName: "Mitchell Marsh",
    from: "DC",
    price: "6.5 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/38.webp",
    description: "All-rounder",
  },
  {
    id: 39,
    playerName: "Pravin Dubey",
    from: "DC",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/39.webp",
    description: "Bowler",
  },
  {
    id: 40,
    playerName: "Ripal Patel",
    from: "DC",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/40.webp",
    description: "Batsman",
  },
  {
    id: 41,
    playerName: "Sarfaraz Khan",
    from: "DC",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/41.webp",
    description: "Batsman",
  },
  {
    id: 42,
    playerName: "Vicky Ostwal",
    from: "DC",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/42.webp",
    description: "Bowler",
  },
  {
    id: 43,
    playerName: "Yash Dhull",
    from: "DC",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/43.webp",
    description: "Batsman",
  },
  {
    id: 44,
    playerName: "Anrich Nortje",
    from: "DC",
    price: "6.5 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/44.webp",
    description: "Bowler",
  },
  {
    id: 45,
    playerName: "Chetan Sakariya",
    from: "DC",
    price: "4.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/45.webp",
    description: "Bowler",
  },
  {
    id: 46,
    playerName: "Kuldeep Yadav",
    from: "DC",
    price: "2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/46.webp",
    description: "Bowler",
  },
  {
    id: 47,
    playerName: "Lungi Ngidi",
    from: "DC",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/47.webp",
    description: "Bowler",
  },
  {
    id: 48,
    playerName: "Mustafizur Rahman",
    from: "DC",
    price: "2 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/48.webp",
    description: "Bowler",
  },
  {
    id: 49,
    playerName: "Shardul Thakur",
    from: "DC",
    price: "10.75 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/49.webp",
    description: "Bowler",
  },
  {
    id: 50,
    playerName: "Khaleel Ahmed",
    from: "DC",
    price: "5.25 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/50.webp",
    description: "Bowler",
  },
  {
    id: 51,
    playerName: "Hardik Pandya",
    from: "GT",
    price: "15 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/51.webp",
    description: "All-rounder",
  },
  {
    id: 52,
    playerName: "Abhinav Manohar",
    from: "GT",
    price: "2.6 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/52.webp",
    description: "Batsman",
  },
  {
    id: 53,
    playerName: "David Miller",
    from: "GT",
    price: "3 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/53.webp",
    description: "Batsman",
  },
  {
    id: 54,
    playerName: "Rahmanullah Gurbaz",
    from: "GT",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/54.webp",
    description: "Batsman",
  },
  {
    id: 55,
    playerName: "Shubman Gill",
    from: "GT",
    price: "8 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/55.webp",
    description: "Batsman",
  },
  {
    id: 56,
    playerName: "Matthew Wade",
    from: "GT",
    price: "2.4 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/56.webp",
    description: "Batsman",
  },
  {
    id: 57,
    playerName: "Wriddhiman Saha",
    from: "GT",
    price: "1.9 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/57.webp",
    description: "Batsman",
  },
  {
    id: 58,
    playerName: "B. Sai Sudharsan",
    from: "GT",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/58.webp",
    description: "All-rounder",
  },
  {
    id: 59,
    playerName: "Darshan Nalkande",
    from: "GT",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/59.webp",
    description: "All-rounder",
  },
  {
    id: 60,
    playerName: "Dominic Drakes",
    from: "GT",
    price: "1.1 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/60.webp",
    description: "Bowler",
  },
  {
    id: 61,
    playerName: "Gurkeerat Mann Singh",
    from: "GT",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/61.webp",
    description: "Batsman",
  },
  {
    id: 62,
    playerName: "Jayant Yadav",
    from: "GT",
    price: "1.7 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/62.webp",
    description: "Bowler",
  },
  {
    id: 63,
    playerName: "Pradeep Sangwan",
    from: "GT",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/63.webp",
    description: "Bowler",
  },
  {
    id: 64,
    playerName: "Rahul Tewatia",
    from: "GT",
    price: "9 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/64.webp",
    description: "Bowler",
  },
  {
    id: 65,
    playerName: "Vijay Shankar",
    from: "GT",
    price: "1.4 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/65.webp",
    description: "All-rounder",
  },
  {
    id: 66,
    playerName: "Alzarri Joseph",
    from: "GT",
    price: "2.4 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/66.webp",
    description: "Bowler",
  },
  {
    id: 67,
    playerName: "Lockie Ferguson",
    from: "GT",
    price: "10 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/67.webp",
    description: "Bowler",
  },
  {
    id: 68,
    playerName: "Mohammad Shami",
    from: "GT",
    price: "6.25 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/68.webp",
    description: "Bowler",
  },
  {
    id: 69,
    playerName: "Noor Ahmad",
    from: "GT",
    price: "0.3 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/69.webp",
    description: "Bowler",
  },
  {
    id: 70,
    playerName: "Sai Kishore",
    from: "GT",
    price: "3 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/70.webp",
    description: "Bowler",
  },
  {
    id: 71,
    playerName: "Rashid Khan",
    from: "GT",
    price: "15 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/71.webp",
    description: "Bowler",
  },
  {
    id: 72,
    playerName: "Varun Aaron",
    from: "GT",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/72.webp",
    description: "Bowler",
  },
  {
    id: 73,
    playerName: "Yash Dayal",
    from: "GT",
    price: "3.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/73.webp",
    description: "Bowler",
  },
  {
    id: 74,
    playerName: "Shreyas Iyer",
    from: "KKR",
    price: "12.25 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/74.webp",
    description: "Batsman",
  },
  {
    id: 75,
    playerName: "Ajinkya Rahane",
    from: "KKR",
    price: "1 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/75.webp",
    description: "Batsman",
  },
  {
    id: 76,
    playerName: "Rinku Singh",
    from: "KKR",
    price: "0.55 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/76.webp",
    description: "Batsman",
  },
  {
    id: 77,
    playerName: "Aaron Finch",
    from: "KKR",
    price: "1.5 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/77.webp",
    description: "Batsman",
  },
  {
    id: 78,
    playerName: "Abhijeet Tomar",
    from: "KKR",
    price: "0.4 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/78.webp",
    description: "Batsman",
  },
  {
    id: 79,
    playerName: "Ramesh Kumar",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/79.webp",
    description: "All-rounder",
  },
  {
    id: 80,
    playerName: "Pratham Singh",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/80.webp",
    description: "Batsman",
  },
  {
    id: 81,
    playerName: "Sam Billings",
    from: "KKR",
    price: "2 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/81.webp",
    description: "Batsman",
  },
  {
    id: 82,
    playerName: "Sheldon Jackson",
    from: "KKR",
    price: "0.6 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/82.webp",
    description: "Batsman",
  },
  {
    id: 83,
    playerName: "Pat Cummins",
    from: "KKR",
    price: "15.5 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/83.webp",
    description: "Bowler",
  },
  {
    id: 84,
    playerName: "Mohammad Nabi",
    from: "KKR",
    price: "1 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/84.webp",
    description: "Bowler",
  },
  {
    id: 85,
    playerName: "Nitish Rana",
    from: "KKR",
    price: "8 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/85.webp",
    description: "Batsman",
  },
  {
    id: 86,
    playerName: "Shivam Mavi",
    from: "KKR",
    price: "3 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/86.webp",
    description: "All-rounder",
  },
  {
    id: 87,
    playerName: "Anukul Roy",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/87.webp",
    description: "All-rounder",
  },
  {
    id: 88,
    playerName: "Chamika Karunaratne",
    from: "KKR",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/88.webp",
    description: "All-rounder",
  },
  {
    id: 89,
    playerName: "Aman Khan",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/89.webp",
    description: "Batsman",
  },
  {
    id: 90,
    playerName: "Andre Russell",
    from: "KKR",
    price: "12 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/90.webp",
    description: "All-rounder",
  },
  {
    id: 91,
    playerName: "Venkatesh Iyer",
    from: "KKR",
    price: "8 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/91.webp",
    description: "All-rounder",
  },
  {
    id: 92,
    playerName: "Umesh Yadav",
    from: "KKR",
    price: "2 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/92.webp",
    description: "Bowler",
  },
  {
    id: 93,
    playerName: "Harshit Rana",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/93.webp",
    description: "Bowler",
  },
  {
    id: 94,
    playerName: "Tim Southee",
    from: "KKR",
    price: "1.5 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/94.webp",
    description: "Bowler",
  },
  {
    id: 95,
    playerName: "Ashok Sharma",
    from: "KKR",
    price: "0.55 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/95.webp",
    description: "Bowler",
  },
  {
    id: 96,
    playerName: "Sunil Narine",
    from: "KKR",
    price: "6 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/96.webp",
    description: "Bowler",
  },
  {
    id: 97,
    playerName: "Varun Chakaravarthy",
    from: "KKR",
    price: "8.4 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/97.webp",
    description: "Bowler",
  },
  {
    id: 98,
    playerName: "Rasikh Dar",
    from: "KKR",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/98.webp",
    description: "Bowler",
  },
  {
    id: 100,
    playerName: "KL Rahul",
    from: "LSG",
    price: "17 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/100.webp",
    description: "Batsman",
  },
  {
    id: 101,
    playerName: "Evin Lewis",
    from: "LSG",
    price: "2 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/101.webp",
    description: "Batsman",
  },
  {
    id: 102,
    playerName: "Manan Vohra",
    from: "LSG",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/102.webp",
    description: "Batsman",
  },
  {
    id: 103,
    playerName: "Manish Pandey",
    from: "LSG",
    price: "4.6 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/103.webp",
    description: "Batsman",
  },
  {
    id: 104,
    playerName: "Quinton de Kock",
    from: "LSG",
    price: "6.75 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/104.webp",
    description: "Batsman",
  },
  {
    id: 105,
    playerName: "Ayush Badoni",
    from: "LSG",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/105.webp",
    description: "All-rounder",
  },
  {
    id: 106,
    playerName: "Deepak Hooda",
    from: "LSG",
    price: "5.75 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/106.webp",
    description: "All-rounder",
  },
  {
    id: 107,
    playerName: "Jason Holder",
    from: "LSG",
    price: "8.75 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/107.webp",
    description: "All-rounder",
  },
  {
    id: 108,
    playerName: "Krishnappa Gowtham",
    from: "LSG",
    price: "0.9 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/108.webp",
    description: "All-rounder",
  },
  {
    id: 109,
    playerName: "Karan Sharma",
    from: "LSG",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/109.webp",
    description: "All-rounder",
  },
  {
    id: 110,
    playerName: "Krunal Pandya",
    from: "LSG",
    price: "8.25 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/110.webp",
    description: "All-rounder",
  },
  {
    id: 111,
    playerName: "Kyle Mayers",
    from: "LSG",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/111.webp",
    description: "All-rounder",
  },
  {
    id: 112,
    playerName: "Marcus Stoinis",
    from: "LSG",
    price: "9.2 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/112.webp",
    description: "All-rounder",
  },
  {
    id: 113,
    playerName: "Ankit Rajpoot",
    from: "LSG",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/113.webp",
    description: "Bowler",
  },
  {
    id: 114,
    playerName: "Avesh Khan",
    from: "LSG",
    price: "10 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/114.webp",
    description: "Bowler",
  },
  {
    id: 115,
    playerName: "Dushmantha Chameera",
    from: "LSG",
    price: "2 Cr",
    isPlaying: false,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/115.webp",
    description: "Bowler",
  },
  {
    id: 116,
    playerName: "Andrew Tye",
    from: "LSG",
    price: "1 Cr",
    isPlaying: true,
    overSeasPlayer: true,
    playerImage:  "./assests/playerImages/116.webp",
    description: "Bowler",
  },
  {
    id: 117,
    playerName: "Mayank Yadav",
    from: "LSG",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/117.webp",
    description: "Bowler",
  },
  {
    id: 118,
    playerName: "Mohsin Khan",
    from: "LSG",
    price: "0.2 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/118.webp",
    description: "Bowler",
  },
  {
    id: 119,
    playerName: "Ravi Bishnoi",
    from: "LSG",
    price: "4 Cr",
    isPlaying: true,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/119.webp",
    description: "Bowler",
  },
  {
    id: 120,
    playerName: "Shahbaz Nadeem",
    from: "LSG",
    price: "0.5 Cr",
    isPlaying: false,
    overSeasPlayer: false,
    playerImage:  "./assests/playerImages/120.webp",
    description: "Bowler",
  },
  {
     id: 121,
     playerName: "Rohit Sharma",
     from: "MI",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/121.webp",
     description: "Batsman",
   },
   {
     id: 122,
     playerName: "Dewald Brewis",
     from: "MI",
     price: "0.5 Cr",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/122.webp",
     description: "Batsman",
   },
   {
     id: 123,
     playerName: "Surya Kumar Yadav",
     from: "MI",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/123.webp",
     description: "Batsman",
   },
   {
     id: 124,
     playerName: "Ishan Kishan",
     from: "MI",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/124.webp",
     description: "Batsman",
   },
   {
     id: 125,
     playerName: "Arjun Tendulakr",
     from: "MI",
     price: "0.5 Cr",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/125.webp",
     description: "Batsman",
   },
   {
     id: 126,
     playerName: "Hrithik Shokeen",
     from: "MI",
     price: "30 Lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/126.webp",
     description: "Batsman",
   },
   {
     id: 127,
     playerName: "Mohd.Arshad Khan",
     from: "MI",
     price: "20 lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/127.webp",
     description: "Bowler",
   },
   {
     id: 128,
     playerName: "N.Tilak Varma",
     from: "MI",
     price: "15 lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/128.webp",
     description: "Bowler",
   },
   {
     id: 129,
     playerName: "Ramndeep Singh",
     from: "MI",
     price: "0.5 Cr",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/129.webp",
     description: "Batsman",
   },
   {
     id: 130,
     playerName: "Tim David",
     from: "MI",
     price: "30 lakh",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/130.webp",
     description: "All Rounder",
   },
   {
     id: 131,
     playerName: "Jasprit Bumrah",
     from: "MI",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/131.webp",
     description: "Bowler",
   },
   {
     id: 132,
     playerName: "Kumar Kartikeya Singh",
     from: "MI",
     price: "05 Lakh",
     isPlaying: false,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/132.webp",
     description: "Bowler",
   },
   {
     id: 133,
     playerName: "Trsitan Stubbs",
     from: "MI",
     price: "10 lakh",
     isPlaying: false,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/133.webp",
     description: "Bowler",
   },
   {
     id: 134,
     playerName: "Akash Madhwal",
     from: "MI",
     price: "10 lakh",
     isPlaying: false,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/134.webp",
     description: "Bowler",
   },

   {
     id: 135,
     playerName: "Faf du Plessis",
     from: "RCB",
     price: "2 cr",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/135.webp",
     description: "Batsman",
   },
   {
     id: 136,
     playerName: "Finn Allen" ,
     from: "RCB",
     price: "2 Cr",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/136.webp",
     description: "Batsman",
   },
   {
     id: 137,
     playerName: "Rajat Patidar" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/137.webp",
     description: "Batsman",
   },
   {
     id: 138,
     playerName: "Virat Kohli" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/138.webp",
     description: "Batsman",
   },
   {
     id: 139,
     playerName: "Anuj Rawat" ,
     from: "RCB",
     price: "50 Lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/139.webp",
     description: "Batsman",
   },
   {
     id: 140,
     playerName: "Dinesh Karthik" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/140.webp",
     description: "Batsman",
   },
   {
     id: 141,
     playerName: "David Willey" ,
     from: "RCB",
     price: "50 Lakh",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/141.webp",
     description: "Bowler",
   },
   {
     id: 142,
     playerName: "Glenn Maxwell" ,
     from: "RCB",
     price: "Reatined",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/142.webp",
     description: "All Rounder",
   },
   {
     id: 143,
     playerName: "Harshal Patel" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/143.webp",
     description: "All Rounder",
   },
   {
     id: 144,
     playerName: "Mahipal Lamror" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/144.webp",
     description: "All Rounder",
   },
   {
     id: 145,
     playerName: "Shahbaz Ahamad" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/145.webp",
     description: "Batsman",
   },
   {
     id: 146,
     playerName: "Suyash S Prabhudessai" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/146.webp",
     description: "All Rounder",
   },
   {
     id: 147,
     playerName: "Wanindu Hasaranga" ,
     from: "RCB",
     price: "70 lakh",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/147.webp",
     description: "Bowler",
   },
   {
     id: 148,
     playerName: "Akash Deep" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/148.webp",
     description: "Bowler",
   },
   {
     id: 149,
     playerName: "Josh Hazlewood" ,
     from: "RCB",
     price: "4 Cr",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/149.webp",
     description: "Bowler",
   },
   {
     id: 150,
     playerName: "Karn Sharma" ,
     from: "RCB",
     price: "Retained",
     isPlaying: false,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/150.webp",
     description: "Bowler",
   },
   {
     id: 151,
     playerName: "Sidharth Kaul" ,
     from: "RCB",
     price: "Retained",
     isPlaying: false,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/151.webp",
     description: "Bowler",
   },
   {
     id: 152,
     playerName: "Mohmd. Siraj" ,
     from: "RCB",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/152.webp",
     description: "Bowler",
   },
   {
     id: 153,
     playerName: "Sikhar Dhawan" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/153.webp",
     description: "Batsman",
   },
   {
     id: 154,
     playerName: "Bhanuka Rajapaksha" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/154.webp",
     description: "Batsman",
   },
   {
     id: 155,
     playerName: "Jitesh Sharma" ,
     from: "PBKS",
     price: "10 cr",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/155.webp",
     description: "Batsman",
   },
   {
     id: 156,
     playerName: "Jonny Baristow" ,
     from: "PBKS",
     price: "7 cr",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/156.webp",
     description: "Batsman",
   },
   {
     id: 157,
     playerName: "Prabhsimran Singh" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/157.webp",
     description: "Batsman",
   },
   {
     id: 158,
     playerName: "Atharva Taide" ,
     from: "PBKS",
     price: "20 lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/158.webp",
     description: "Batsman",
   },
   {
     id: 159,
     playerName: "Harpeet Brar" ,
     from: "PBKS",
     price: "10 lakh",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/159.webp",
     description: "Bowler",
   },
   {
     id: 160,
     playerName: "Liam Livingstone" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/160.webp",
     description: "All Rounder",
   },
   {
     id: 161,
     playerName: "Raj Angad Bawa" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/161.webp",
     description: "All Rounder",
   },
   {
     id: 162,
     playerName: "Rishi Dhawan" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/162.webp",
     description: "All Rounder",
   },{
     id: 163,
     playerName: "Sharukh Khan" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/163.webp",
     description: "All Rounder",
   },
   {
     id: 164,
     playerName: "Arshdeep Singh" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/164.webp",
     description: "Bowler",
   },
   {
     id: 165,
     playerName: "Baltej Dhanda" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/165.webp",
     description: "Bowler",
   },
   {
     id: 166,
     playerName: "Kagiso Rabada" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/166.webp",
     description: "Bowler",
   },
   {
     id: 167,
     playerName: "Nathan Ellis" ,
     from: "PBKS",
     price: "50 lakhs",
     isPlaying: true,
     overSeasPlayer: true,
     playerImage:  "./assests/playerImages/167.webp",
     description: "Batsman",
   },
   {
     id: 168,
     playerName: "Rahul Chahar" ,
     from: "PBKS",
     price: "Retained",
     isPlaying: true,
     overSeasPlayer: false,
     playerImage:  "./assests/playerImages/168.webp",
     description: "Bowler",
   },
   {
      id: 169,
      playerName: "Sanju Samson" ,
      from: "RR",
      price: "15cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/169.webp",
      description: "Batsman/WC",
    },
    {
      id: 170,
      playerName: "Devdutt Padikkal" ,
      from: "RR",
      price: "7.75cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/170.webp",
      description: "Batsman",
    },
    {
      id: 171,
      playerName: "Jos Buttler" ,
      from: "RR",
      price: "10cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/171.webp",
      description: "Batsman/WC",
    },
    {
      id: 172,
      playerName: "Shimron Hetmyer" ,
      from: "RR",
      price: "10cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/172.webp",
      description: "Batsman",
    },
    {
      id: 173,
      playerName: "Yashasvi Jaiswal" ,
      from: "RR",
      price: "retained",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/173.webp",
      description: "Batsman",
    },
    {
      id: 174,
      playerName: "Dhruv Jurel" ,
      from: "RR",
      price: "retained",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/174.webp",
      description: "WC",
    },
    {
      id: 175,
      playerName: "Ravichandran Ashwin" ,
      from: "RR",
      price: "11cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/175.webp",
      description: "ALLROUNDER",
    },
    {
      id: 176,
      playerName: "Riyan Parag" ,
      from: "RR",
      price: "2cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/176.webp",
      description: "AllRounder",
    },
    {
      id: 177,
      playerName: "KC Cariappa" ,
      from: "RR",
      price: "3cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/177.webp",
      description: "Bowler",
    },
    {
      id: 178,
      playerName: "Kuldip Sen" ,
      from: "RR",
      price: "1cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/178.webp",
      description: "Bowler",
    },
    {
      id: 179,
      playerName: "Kuldip Yadav" ,
      from: "RR",
      price: "70lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/179.webp",
      description: "Bowler",
    },
    {
      id: 180,
      playerName: "Navdeep Saini" ,
      from: "RR",
      price: "50lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/180.webp",
      description: "Bowler",
    },
    {
      id: 181,
      playerName: "Obed McCoy" ,
      from: "RR",
      price: "1cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/181.webp",
      description: "Bowler",
    },
    {
      id: 182,
      playerName: "Prasidh Krishna" ,
      from: "RR",
      price: "40lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/182.webp",
      description: "Bowler",
    },
    {
      id: 183,
      playerName: "Trent Boult" ,
      from: "RR",
      price: "10cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/183.webp",
      description: "Bowler",
    },
    {
      id: 184,
      playerName: "Yuzvendra Chahal" ,
      from: "RR",
      price: "12cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/184.webp",
      description: "Bowler",
    },
    {
      id: 185,
      playerName: "Abdul Samad" ,
      from: "SRH",
      price: "15cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/185.webp",
      description: "Batsman",
    },
    {
      id: 186,
      playerName: "Aiden Markram" ,
      from: "SRH",
      price: "10cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/186.webp",
      description: "Batsman",
    },
    {
      id: 187,
      playerName: "Rahul Tripathi" ,
      from: "SRH",
      price: "0.8cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/187.webp",
      description: "Batsman",
    },
    {
      id: 188,
      playerName: "Glenn Philips" ,
      from: "SRH",
      price: "10cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/188.webp",
      description: "Batsman/WC",
    },
    {
      id: 189,
      playerName: "Abhishek Sharma" ,
      from: "SRH",
      price: "2cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/189.webp",
      description: "All Rounder",
    },
    {
      id: 190,
      playerName: "Marco Jansen" ,
      from: "SRH",
      price: "5cr",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/190.webp",
      description: "AllRounder",
    },
    {
      id: 191,
      playerName: "Washington Sundar" ,
      from: "SRH",
      price: "7cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/191.webp",
      description: "AllRounder",
    },
    {
      id: 192,
      playerName: "Bhuvneshwar Kumar" ,
      from: "SRH",
      price: "8cr",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/192.webp",
      description: "Bowler",
    },
    {
      id: 193,
      playerName: "Fazalhaq Farooqi" ,
      from: "SRH",
      price: "80lakh",
      isPlaying: true,
      overSeasPlayer: true,
      playerImage:  "./assests/playerImages/193.webp",
      description: "Bowler",
    },
    {
      id: 194,
      playerName: "Kartik Tyagi" ,
      from: "SRH",
      price: "50lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/194.webp",
      description: "Bowler",
    },
    {
      id: 195,
      playerName: "T Natarajan" ,
      from: "SRH",
      price: "80lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/195.webp",
      description: "Bowler",
    },
    {
      id: 196,
      playerName: "Umran Malik" ,
      from: "SRH",
      price: "40lakh",
      isPlaying: true,
      overSeasPlayer: false,
      playerImage:  "./assests/playerImages/196.webp",
      description: "Bowler",
    },


    
    
   
];
 
// 
 
var teamData = [
  {
      "id": 0,
      "teamFullName": "Mumbai Indians",
      "sName": "MI",
      "fullSname": "MI (Mumbai Indians)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/MI/Logos/Roundbig/MIroundbig.png",
      "teamImage" : "./assests/header1.webp",
      "WonCount": 5,
      "TopBatsman" : "Rohit Sharma",
      "TopBowler" : "Jasprit Bumrah",
      "Captain" : "Rohit Sharma",
      "Homeground" :  "Wankhade Stadium",
      "WinningYear" : "2013, 2015, 2017, 2019, 2020",
  },
  {
      "id": 1,
      "teamFullName": "Chennai Super Kings",
      "sName": "CSK",
      "fullSname": "CSK (Chennai Super King)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/CSK/logos/Roundbig/CSKroundbig.png",
      "teamImage" : "./assests/csk1.jpg",
      "WonCount": 4,
      "TopBatsman" : "Ravindra jadeja",
      "TopBowler" : "Deepak Chahar",
      "Captain" : "M.S.Dhoni",
      "Homeground" :  "Chepak",
      "WinningYear" : "2010, 2011, 2018, 2021",
  },
  {
      "id": 2,
      "teamFullName": "Royal Challengers Bangalore",
      "sName": "RCB",
      "fullSname": "RCB (Royal challengers Bangalore)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RCB/Logos/Roundbig/RCBroundbig.png",
      "teamImage" : "./assests/header2.jpg",
      "WonCount": 0,
      "TopBatsman" : "Virat Kohli",
      "TopBowler" : "Mohmd. Siraj",
      "Captain" : "Faf Du Plesis",
      "Homeground" :  "M. Chinnaswamy Stadium",
      "WinningYear" : "No Trophies",
  },
  {
      "id": 3,
      "teamFullName": "Kolkata Knight Riders",
      "sName": "KKR",
      "fullSname": "KKR (Kolkata Knight Riders)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/KKR/Logos/Roundbig/KKRroundbig.png",
      "teamImage" : "./assests/kkr.webp",
      "WonCount": 2,
      "TopBatsman" : "Eon Morgan",
      "TopBowler" : "Andrew Rusell",
      "Captain" : "Eon Morgan",
      "Homeground" :  "Eden Gardens",
      "WinningYear" : "2012 , 2014",
  },
  {
      "id": 4,
      "teamFullName": "Delhi Capitals",
      "sName": "DC",
      "fullSname": "DC (Delhi Capitals)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/DC/Logos/Roundbig/DCroundbig.png",
      "teamImage" : "./assests/dc1.jpg",
      "WonCount": 2,
      "TopBatsman" : "Rishab Panth",
      "TopBowler" : "Khaleel Ahmad",
      "Captain" : "Rishab Pant",
      "Homeground" :  "Arun Jaitley Stadium",
      "WinningYear" : "No Trophies",
  },
  {
      "id": 5,
      "teamFullName": "Gujarat Titan",
      "sName": "GT",
      "fullSname": "GT (Gujarat Tistan)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/GT/Logos/Roundbig/GTroundbig.png",
      "teamImage" : "./assests/gt1.jpg",
      "WonCount": 2,
      "TopBatsman" : "David Miller",
      "TopBowler" : "Mohmd.Shami",
      "Captain" : "Hardik Pandya",
      "Homeground" :  "Narendra Modi Stadium",
      "WinningYear" : "2022",
  },

  {
      "id": 6,
      "teamFullName": "Rajasthan Royals",
      "sName": "RR",
      "fullSname": "RR (Rajasthan Royals)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RR/Logos/Roundbig/RRroundbig.png",
      "teamImage" : "./assests/rr1.jpg",
      "WonCount": 1,
      "TopBatsman" : "Jos Butler",
      "TopBowler" : "Ben Stoke",
      "Captain" : "Jos Butler",
      "Homeground" :  "Sawai Mansingh Stadium",
      "WinningYear" : "2008",
  },
  {
      "id": 7,
      "teamFullName": "Sunrises Hyderabad",
      "sName": "SRH",
      "fullSname": "SH (Sunrises Hyderabad)",
      "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/SRH/Logos/Roundbig/SRHroundbig.png",
      "teamImage" : "./assests/srh1.webp",
      "WonCount": 1,
      "TopBatsman" : "Kane WilliamSon",
      "TopBowler" : "Rashid",
      "Captain" : "Kane Williamson",
      "Homeground" :  "Rajiv Gandhi Intl. Stadium",
      "WinningYear" : " 2016",
  },
  {
    "id": 8,
    "teamFullName": "Lucknow Super Giants",
    "sName": "LSG",
    "fullSname": "Lucknow Super Giants",
    "teamIcon": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/LSG/Logos/Roundbig/LSGroundbig.png",
    "teamImage" : "./assests/lcg1.webp",
    "WonCount": 0,
    "TopBatsman" : "KL Rahul",
    "TopBowler" : "Rashid",
    "Captain" : "K.L.Rahul",
    "Homeground" :  "BRSABV Cricket Stadium",
    "WinningYear" : "No Trophies",
},



];




function saveData(){
   if (JSON.parse(localStorage.getItem("playerDetails" )) === null) {
      localStorage.setItem('playerDetails', JSON.stringify(playerDetails));
   }
}
function saveTeamData(){
  if (JSON.parse(localStorage.getItem("TeamDetails" )) === null) {
     localStorage.setItem('TeamDetails', JSON.stringify(teamData));
  }
}


